name: Generate and Publish JCR Intros

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install gspread google-api-python-client oauth2client pillow

      - name: Run script
        run: python generate_intro.py

      - name: Clone public repo
        run: |
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO_PAT }}@github.com/ShizheL/Oriel_JCR_Intros_Public.git public_repo
          rm -rf public_repo/images
          mkdir -p public_repo/images
          cp generated_images/*.png public_repo/images/

      - name: Commit and push to public repo
        run: |
          cd public_repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update generated intros" || echo "Nothing to commit"
          git push
